name = "Exquisite Corpse"

[store]
id="com.github.M4ss1ck.exquisitecorpse"
version_name=1.0
version_code=1
author="M4ss1ck"
author_email="massick@systemli.org"
description="A social creative writing game for Delta Chat"